[project]
name = "langflow-pipelines"
version = "0.1.0"
description = "GenAI pipelines to assist people with integration into Finland"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langflow>=1.3.2",
]
